import assert from "node:assert/strict"
import { readFileSync } from "node:fs"
import test from "node:test"

import { decodeBase64Utf8, encodeBase64Utf8 } from "../lib/utilities/base64.ts"

const fixtures = JSON.parse(
  readFileSync(
    new URL("./fixtures/bookmark-export-compatibility.json", import.meta.url),
    "utf8"
  )
)

test("decodes exports generated by js-base64", () => {
  for (const fixture of Object.values(fixtures)) {
    assert.deepEqual(
      JSON.parse(decodeBase64Utf8(fixture.serialized.slice(2))),
      fixture.payload
    )
  }
})

test("preserves the current v5 export format for Unicode content", () => {
  const fixture = fixtures.v5Unicode

  assert.equal(
    encodeBase64Utf8(JSON.stringify(fixture.payload)),
    fixture.serialized.slice(2)
  )
})
